### ISSUE TITLE
5GNR JSON Cell Identity string is 4 bits too long

### ISSUE THREAD

**Issue by jewalt** [pycrate-org/pycrate#18]
In decoding a 5G SIB1, the CellAccessRelatedInfo->PLMN-identityList->CellIdentity is correct when converted to_asn1(), but to_json() returns a string that has a zero in the least significant nibble position (the value is shifted left by 4 bits).  

According to the spec, this should be a 36-bit string.  As I said, this is stored correctly, but only is a problem with to_json.  For exmaple, if the cellIdentity is '022ea200c', calling to_asn1() returns, "'022EA200C'H".  Calling to_json() return '"022ea200c0"'

>>> ci._val
(585768972, 36)
>>> ci.to_asn1()
"'022EA200C'H"
>>> ci.to_json()
'"022ea200c0"'

It looks like this is because uint_to_hex is shifting the value to be word aligned, but that doesn't make sense for cellIdentity, or a BIT_STRING in general.  

Is this a known issue with the JSON representation and non-word-aligned BIT_STRINGs?

**Comment by mitshell** [comment]
This actually corresponds to the official ITU-T JER encoding (see <https://www.itu.int/rec/T-REC-X.697-202102-I>). Section 24.2.1 states: 
```
The encoding of a bitstring value with a fixed size shall be a JSON string. The Unicode character string denoted by the JSON string shall consist of an even number of the hexadecimal digits 0123456789abcdefABCDEF, with each consecutive pair of digits encoding one group of eight consecutive bits in the bitstring value. If the length of the bitstring value is not a multiple of 8 bits, the bitstring value shall be encoded as if it contained extra bits, up to the next multiple of 8, all set to zero.
```
I admit this may not be the best choice for encoding unaligned strings, but doing otherwise in pycrate would break the compatibility with JER.

**Comment by jewalt** [comment]
That is confusing.  Thank you for the pointer to the ITU-T JER document.  Knowing this, I will modify my code to accept the extra 4 bits.  Thank you again!
