### ISSUE TITLE
pycrate_mobile/TS24526_UEPOL RouteSelectDescComp Time Window should contain starttime and stoptime

### ISSUE THREAD

**Issue by madjcsg** [pycrate-org/pycrate#19]
From TS 24.526 Table 5.2.1: UE policy part contents including a URSP rule 
> For "time window type", the route selection descriptor component value field shall be encoded as a sequence of a Starttime field and a Stoptime field. The Starttime field is represented by the number of seconds since 00:00:00 on 1 January 1970 and is encoded as the 64-bit NTP timestamp format defined in IETF RFC 5905 [17], where binary encoding of the integer part is in the first 32 bits and binary encoding of the fraction part in the last 32 bits. The encoding of the Stoptime filed is the same as the Starttime field.

The current implementation uses a type which represents a single instance of `time` (seconds and fraction), rather than a sequence of `time`s.

https://github.com/pycrate-org/pycrate/blob/0b8309e258c59de9d0d7e6da31566097c92f224b/pycrate_mobile/TS24526_UEPOL.py#L361

**Comment by mitshell** [comment]
True !
The fix is provided with https://github.com/pycrate-org/pycrate/commit/8c34e34e6895440ad95890c688f1c3ad4c6bb746
